# Generated by Django 3.2.23 on 2024-04-11 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userInfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='')),
                ('upload_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userInfo.user')),
            ],
        ),
    ]
